### ISSUE TITLE
Aligning Rows on Import

### ISSUE THREAD

**Issue by sarcanon** [HelenFoster/AnkiSpreadsheetImportPlus#1]
Hi. This add-on seems like it will precisely fill a need I have. But I have a couple of questions that don't appear to be answered on the Add-On page on ankiweb.net.

1. When importing a spreadsheet into an existing deck, how does the plug-in match the row being imported to the existing row in the deck? Presumably it tries to match on the values in the first field, but what if they aren't unique? How does it determine which card will be modified?

2. May I assume that updating an existing deck only modifies the fields in the spreadsheet being imported, i.e., no due date information in the existing card will be modified?

Thank you.

**Comment by HelenFoster** [comment]
Hi, this addon doesn't actually modify the deck directly, but only processes the data for Anki's import code. So the behaviour should be the same as importing a text file, as described in Anki's manual. (The manual doesn't cover all the edge cases, but for the same reason, I didn't actually need to know them in order to write this.)

Anki expects the first field to be unique. If there's no real field which is both unique and unlikely to be edited, it's generally recommended to add an ID field.

The "edited" date gets updated, but scheduling information is left alone.
